### ISSUE TITLE
How is the goundtruth of edge generated?

### ISSUE THREAD

**Issue by LiYAnErr** [taozh2017/FAPNet#1]
Hello, this paper is very enlightening to me. However, I am a little confused about how the goundtruth of edge generated. Could you tell me the generation process of the goundtruth of edge? Thanks a lot!!

**Comment by taozh2017** [comment]
The ground-truth edges can be extracted by using a Canny edge detector.
Thanks.

**Comment by LiYAnErr** [comment]
Thank you very much！
